using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.IO;
using System.Text;
using System.Configuration.Assemblies;
using System.Data.OleDb;
public partial class BD_Mis : System.Web.UI.Page
{
    CCommon objconn = new CCommon();
    DataSet ds = new DataSet();
    MIS objMis = new MIS();
    OleDbDataAdapter da;
    DataTable dd_table = new DataTable();
    DataRow drow_row ;
    String sql;
    int cnt;
    String MYSQL;
    String BDCODE;
    String CLIENTCODE; 
     protected void Page_Load(object sender, EventArgs e)
    {
        string UserId = Session["UserId"].ToString();
        {
            if ("101103557" == UserId || "101103553" == UserId || "101103550" == UserId || "101103549" == UserId || "101103551" == UserId || "101103552" == UserId || "101103556" == UserId || "101103555" == UserId || "101103554" == UserId)
            BTN_VIEW.Visible = false;
            BTN_EXPORT.Visible = false;
            lblMsg.Text = "U are not authorised";
        }
        lblMsg.Text = "";
    }
      protected void DDL_BD_DataBound(object sender, EventArgs e)
    {
        DDL_BD.Items.Insert(0, new ListItem("--ALL--","0"));
    }
    protected void DDL_Client_DataBound(object sender, EventArgs e)
    {
        DDL_CLIENT.Items.Insert(0, new ListItem("--ALL--", "0"));
    }
    protected void DDL_ACTIVITY_DataBound(object sender, EventArgs e)
    {
        DDL_ACTIVITY.Items.Insert(0, new ListItem("--ALL--", "0"));
    }
    protected void DDL_PRODUCT_DataBound(object sender, EventArgs e)
    {
        DDL_PRODUCT.Items.Insert(0, new ListItem("--ALL--", "0"));
    }    
    protected void BTN_VIEW_Click(object sender, EventArgs e)
    {
       
        if ((RBTN_BD.Checked == false) && (RBTN_CLIENT.Checked == false))
        {
            Page.ClientScript.RegisterStartupScript(GetType(), "Bipin", "alert('Please Select Rm Wise or Client Wise Report!!')", true);
        }
           else

            if (RBTN_BD.Checked == true)
            {
                dd_table.Columns.Add("Presale Ref No");
                dd_table.Columns.Add("Client");
                dd_table.Columns.Add("Activity");
                dd_table.Columns.Add("Product");
                dd_table.Columns.Add("Lead Generated by");
                dd_table.Columns.Add("Lead Generate date");
                dd_table.Columns.Add("Contract Status");
                dd_table.Columns.Add("Close Date");
                dd_table.Columns.Add("Meeting Details");
                if (DDL_BD.SelectedValue == "0")
                {
                    for (int m = 0; m < Convert.ToInt32(DDL_BD.Items.Count); m++)
                    {
                        objMis.BDCode = DDL_BD.Items[m].Value;
                        BDCODE = objMis.BDCode;
                                          
                        if (BDCODE != "0")
                        {
                            MYSQL = "";
                            objMis.ClientCode = DDL_CLIENT.SelectedValue;
                            objMis.ActivityCode = DDL_ACTIVITY.SelectedValue;
                            objMis.ProductCode = DDL_PRODUCT.SelectedValue;
                            cnt = 0;
                            MYSQL = objMis.GetAllBd();
                            OleDbConnection conn = new OleDbConnection(objconn.ConnectionString);
                            da = new OleDbDataAdapter(MYSQL, conn);
                            da.Fill(ds, "Temp");
                            da.Dispose();
                            conn.Close();
                            
                            if (ds.Tables["temp"].Rows.Count > 0)
                            {
                                for (int i = 0; i < Convert.ToInt32(ds.Tables["temp"].Rows.Count.ToString()); i++)
                                {
                                    sql = "";
                                    sql = objMis.Get_Bd_NAme();
                                    conn.Open();
                                    da = new OleDbDataAdapter(sql, conn);
                                    da.Fill(ds, "bd");
                                    conn.Close();
                                    if (cnt == 0)
                                    {
                                        drow_row = dd_table.NewRow();
                                        drow_row[0] = " BD Manager:" + ds.Tables["bd"].Rows[0]["fullname"];
                                       // drow_row[0] ="<p align='left' style='Font-weight:bold; COLOR: red' >" + managername + "</p>";
                                        cnt = 1;
                                        dd_table.Rows.Add(drow_row);
                                       
                                    }
                                    ds.Tables["bd"].Rows.Clear();
                                    drow_row = dd_table.NewRow();
                                    drow_row[0] = ds.Tables["temp"].Rows[i]["Cont_Presale_Ref_No"];
                                    drow_row[1] = ds.Tables["temp"].Rows[i]["Client_Name"];
                                    drow_row[2] = ds.Tables["temp"].Rows[i]["Activity_Name"];
                                    drow_row[3] = ds.Tables["temp"].Rows[i]["Product_Name"];
                                    drow_row[4] = ds.Tables["temp"].Rows[i]["Lead_Ganerated_By"];
                                    drow_row[5] = ds.Tables["temp"].Rows[i]["Lead_Generated_Date"];
                                    drow_row[6] = ds.Tables["temp"].Rows[i]["Contract_Status"];
                                    drow_row[7] = ds.Tables["temp"].Rows[i]["Close_Date"];
                                    dd_table.Rows.Add(drow_row);
                                }

                               ds.Tables["temp"].Rows.Clear();
                            }

                            else
                            {
                                GridView1.DataSource = "";
                                GridView1.DataBind();
                            }

                        }
                     
                    }

                    GridView1.DataSource = dd_table;
                    GridView1.DataBind();
                           
                }

                //###### for particular bd wise ######## 
                if (DDL_BD.SelectedValue != "0")
                {
                    cnt = 0;
                    objMis.BDCode = DDL_BD.SelectedValue;
                    objMis.ClientCode = DDL_CLIENT.SelectedValue;
                    objMis.ActivityCode = DDL_ACTIVITY.SelectedValue;
                    objMis.ProductCode = DDL_PRODUCT.SelectedValue;
                    MYSQL = objMis.GetParticularBd();
                    OleDbConnection conn = new OleDbConnection(objconn.ConnectionString);
                    da = new OleDbDataAdapter(MYSQL, conn);
                    da.Fill(ds, "Temp");
                    dd_table.Dispose();
                    conn.Close();
                    if (ds.Tables["temp"].Rows.Count > 0)
                    {
                        for (int i = 0; i < Convert.ToInt32(ds.Tables["temp"].Rows.Count.ToString()); i++)
                        {
                            sql = "";
                            sql = objMis.Get_Bd_NAme();
                            conn.Open();
                            da = new OleDbDataAdapter(sql, conn);
                            da.Fill(ds, "bd");
                            dd_table.Dispose();
                            conn.Close();
                            if (cnt == 0)
                            {
                                drow_row = dd_table.NewRow();
                                drow_row[0] = "BD Manager:" + ds.Tables["bd"].Rows[0]["fullname"];
                                //drow[0] = "<p align='right' style='Font-weight:bold; COLOR: navy' >" + "BD Manager_NAME:" + ds.Tables["bd"].Rows[0][0] + "</p>";
                                cnt = 1;
                                dd_table.Rows.Add(drow_row);
                            }
                            ds.Tables["bd"].Rows.Clear();
                            drow_row = dd_table.NewRow();
                            drow_row[0] = ds.Tables["temp"].Rows[i]["Cont_Presale_Ref_No"];
                            drow_row[1] = ds.Tables["temp"].Rows[i]["Client_Name"];
                            drow_row[2] = ds.Tables["temp"].Rows[i]["Activity_Name"];
                            drow_row[3] = ds.Tables["temp"].Rows[i]["Product_Name"];
                            drow_row[4] = ds.Tables["temp"].Rows[i]["Lead_Ganerated_By"];
                            drow_row[5] = ds.Tables["temp"].Rows[i]["Lead_Generated_Date"];
                            drow_row[6] = ds.Tables["temp"].Rows[i]["Contract_Status"];
                            drow_row[7] = ds.Tables["temp"].Rows[i]["Close_Date"];
                            dd_table.Rows.Add(drow_row);
                        }
                        ds.Tables["temp"].Rows.Clear();
                        GridView1.DataSource = dd_table;
                        GridView1.DataBind();
                    }
                    else
                    {
                        GridView1.DataSource = "";
                        GridView1.DataBind();
                    }
                }
              }

                    if (RBTN_CLIENT.Checked == true)
                    {
                        dd_table.Columns.Add("Presale Ref No");
                        dd_table.Columns.Add("BD Manager");
                        dd_table.Columns.Add("Activity");
                        dd_table.Columns.Add("Product");
                        dd_table.Columns.Add("Lead Generated by");
                        dd_table.Columns.Add("Lead Generate date");
                        dd_table.Columns.Add("Contract Status");
                        dd_table.Columns.Add("Close Date");
                        dd_table.Columns.Add("Meeting Details");
                        if (DDL_CLIENT.SelectedValue == "0")
                        {

                            for (int m = 0; m < Convert.ToInt32(DDL_CLIENT.Items.Count); m++)
                            {
                                
                                 objMis.ClientCode = DDL_CLIENT.Items[m].Value;
                                 CLIENTCODE = objMis.ClientCode;
                                 if (CLIENTCODE != "0")
                                {

                                   objMis.BDCode = DDL_BD.SelectedValue;
                                   objMis.ActivityCode = DDL_ACTIVITY.SelectedValue;
                                   objMis.ProductCode = DDL_PRODUCT.SelectedValue;                                                  
                                   MYSQL = "";
                                   cnt = 0;
                                   MYSQL = objMis.GetAllClient();
                                   OleDbConnection conn = new OleDbConnection(objconn.ConnectionString);
                                   da = new OleDbDataAdapter(MYSQL, conn);
                                   da.Fill(ds, "Temp");
                                   dd_table.Dispose();
                                   conn.Close();
                                   if (ds.Tables["temp"].Rows.Count > 0)
                                    {
                                        for (int i = 0; i < Convert.ToInt32(ds.Tables["temp"].Rows.Count.ToString()); i++)
                                        {
                                              sql = "";
                                              sql = objMis.Get_Client_Name();
                                              da = new OleDbDataAdapter(sql, conn);
                                              da.Fill(ds, "bd");
                                              dd_table.Dispose();
                                              conn.Close();
                                             if (cnt == 0)
                                                {
                                                drow_row = dd_table.NewRow();
                                                drow_row[0] = "Client Name:" + ds.Tables["bd"].Rows[0]["Client_Name"];
                                                // drow_row[0] = "<p align='right' style='Font-weight:bold; COLOR: navy' >" + "BD Manager_NAME:" + ds.Tables["bd"].Rows[0][0]  "</p>";
                                                cnt = 1;
                                                dd_table.Rows.Add(drow_row);
                                                }
                                            ds.Tables["bd"].Rows.Clear();
                                            drow_row = dd_table.NewRow();
                                            drow_row[0] = ds.Tables["temp"].Rows[i]["Cont_Presale_Ref_No"];
                                            drow_row[1] = ds.Tables["temp"].Rows[i]["BD_Manager"];
                                            drow_row[2] = ds.Tables["temp"].Rows[i]["Activity_Name"];
                                            drow_row[3] = ds.Tables["temp"].Rows[i]["Product_Name"];
                                            drow_row[4] = ds.Tables["temp"].Rows[i]["Lead_Ganerated_By"];
                                            drow_row[5] = ds.Tables["temp"].Rows[i]["Lead_Generated_Date"];
                                            drow_row[6] = ds.Tables["temp"].Rows[i]["Contract_Status"];
                                            drow_row[7] = ds.Tables["temp"].Rows[i]["Close_Date"];
                                            dd_table.Rows.Add(drow_row);
                                        }
                                      ds.Tables["temp"].Rows.Clear();
                                    }
                                    else
                                    {
                                        GridView1.DataSource = "";
                                        GridView1.DataBind();
                                    }
                                }
                            }
                            GridView1.DataSource = dd_table;
                            GridView1.DataBind();
                                      
                        }
                        else
                        {
                            GridView1.DataSource = "";
                            GridView1.DataBind();
                        }

                        //###### for particular CLIENT wise ######## 
                        if (DDL_CLIENT.SelectedValue != "0")
                        {
                            cnt = 0;
                            objMis.ClientCode = DDL_CLIENT.SelectedValue;
                            objMis.BDCode = DDL_BD.SelectedValue;
                            objMis.ActivityCode = DDL_ACTIVITY.SelectedValue;
                            objMis.ProductCode = DDL_PRODUCT.SelectedValue;  
                            MYSQL = objMis.GetParticularClient();
                            OleDbConnection conn = new OleDbConnection(objconn.ConnectionString);
                            da = new OleDbDataAdapter(MYSQL, conn);
                            da.Fill(ds, "Temp");
                            conn.Close();
                         if (ds.Tables["temp"].Rows.Count > 0)
                            {
                                for (int i = 0; i < Convert.ToInt32(ds.Tables["temp"].Rows.Count.ToString()); i++)
                                {
                                    sql = "";
                                    sql = objMis.Get_Client_Name();
                                    conn.Open();
                                    da = new OleDbDataAdapter(sql, conn);
                                    da.Fill(ds, "bd");
                                    conn.Close();
                                  if (cnt == 0)
                                    {
                                        drow_row = dd_table.NewRow();
                                        drow_row[0] = "Client Name:" + ds.Tables["bd"].Rows[0]["Client Name"];
                                        //drow[0] = "<p align='right' style='Font-weight:bold; COLOR: navy' >" + "BD Manager_NAME:" + ds.Tables["bd"].Rows[0][0] + "</p>";
                                        cnt = 1;
                                        dd_table.Rows.Add(drow_row);
                                    }
                                    ds.Tables["bd"].Rows.Clear();
                                    drow_row = dd_table.NewRow();
                                    drow_row[0] = ds.Tables["temp"].Rows[i]["Cont Presale Ref No"];
                                    drow_row[1] = ds.Tables["temp"].Rows[i]["BD Manager"];
                                    drow_row[2] = ds.Tables["temp"].Rows[i]["Activity Name"];
                                    drow_row[3] = ds.Tables["temp"].Rows[i]["Product Name"];
                                    drow_row[4] = ds.Tables["temp"].Rows[i]["Lead Ganerated By"];
                                    drow_row[5] = ds.Tables["temp"].Rows[i]["Lead Generated Date"];
                                    drow_row[6] = ds.Tables["temp"].Rows[i]["Contract_Status"];
                                    drow_row[7] = ds.Tables["temp"].Rows[i]["Close Date"];
                                    dd_table.Rows.Add(drow_row);
                                }
                                GridView1.DataSource = dd_table;
                                GridView1.DataBind();
                              ds.Tables["temp"].Rows.Clear();
                            }
                            else
                            {
                                GridView1.DataSource = "";
                                GridView1.DataBind();
                            }
                        }

                    }
                }
    
    protected void BTN_EXPORT_Click(object sender, EventArgs e)
    {  
       //Export the GridView to Excel
        String rpt_header = "M I S - R E P O R T";
        if (GridView1.Rows.Count > 0)
        {
            PrepareGridViewForExport(GridView1);
            ExportGridView(rpt_header);
        }
        else
        {
            lblMsg.Text = "No record to import.";
        }
    }
    private void ExportGridView(String rpt_header)
    {
        string attachment = "attachment; filename=Contacts.xls";
        Response.ClearContent();
        Response.AddHeader("content-disposition", attachment);
        Response.ContentType = "application/ms-excel";
        StringWriter sw = new StringWriter();
        System.Web.HttpContext.Current.Response.Write("<IMG height='25px' width='150px' src='" + Server.MapPath("../../Images/pamaclogo.gif") + "'>");
        System.Web.HttpContext.Current.Response.Write("<b><center><font size=3 face=Verdana color=white> " + " gg " + "</font></center></b>");
        System.Web.HttpContext.Current.Response.Write("<b><center><font size=3 face=Verdana color=white> " + " gg " + "</font></center></b>");
        System.Web.HttpContext.Current.Response.Write("<b><center><font size=3 face=Verdana color=white> " + " gg " + "</font></center></b>");
        System.Web.HttpContext.Current.Response.Write("<b><center><font size=3 face=Verdana color=white> " + " gg " + "</font></center></b>");
        System.Web.HttpContext.Current.Response.Write("<b><center><font size=3 face=Verdana color=#0000FF>"  + rpt_header + "</font></center></b>");
        HtmlTextWriter htw = new HtmlTextWriter(sw);
        GridView1.RenderControl(htw);
        Response.Write(sw.ToString());
        Response.End();
    }
    public override void VerifyRenderingInServerForm(Control control)
    {

    }
     private void 
         PrepareGridViewForExport(Control gv)
    {
        LinkButton lb = new LinkButton();
        Literal l = new Literal();
        string name = String.Empty;
        for (int i = 0; i < gv.Controls.Count; i++)
        {
            if (gv.Controls[i].GetType() == typeof(LinkButton))
            {
                l.Text = (gv.Controls[i] as LinkButton).Text;
                gv.Controls.Remove(gv.Controls[i]);
                gv.Controls.AddAt(i, l);
            }
            else if (gv.Controls[i].GetType() == typeof(DropDownList))
            {
                l.Text = (gv.Controls[i] as DropDownList).SelectedItem.Text;
                gv.Controls.Remove(gv.Controls[i]);
                gv.Controls.AddAt(i, l);
            }
            else if (gv.Controls[i].GetType() == typeof(CheckBox))
            {
                l.Text = (gv.Controls[i] as CheckBox).Checked ? "True" : "False";
                gv.Controls.Remove(gv.Controls[i]);
                gv.Controls.AddAt(i, l);
            }
            if (gv.Controls[i].HasControls())
            {
                PrepareGridViewForExport(gv.Controls[i]);
            }
         }
    }
}





    

